name: pulsar-lst1
channels:
  - default
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - astropy
  - ctapipe~=0.19.2
  - gammapy==1.1
  - h5py
  - iminuit>=2
  - ipython
  - joblib
  - jupyter
  - matplotlib~=3.7
  - numba
  - numpy=1.21
  - c-blosc2
  - protozfits=2.0
  - protobuf=3.20
  - pandas
  - pyyaml
  - scipy
  - vitables
  - jplephem
  - zstandard
  - lstchain==0.10.6
  - pint-pulsar<=0.9.7
  - more-itertools==10.4.0
