name: pulsar-lst4
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - astropy
  - ctapipe~=0.19.2
  - gammapy~=1.1
  - h5py
  - iminuit>=2
  - ipython
  - joblib
  - jupyter
  - matplotlib~=3.7
  - numba
  - numpy
  - pandas
  - pyyaml
  - scipy
  - vitables
  - jplephem
  - zstandard
  - lstchain==0.10.6
  - more-itertools==10.4.0
  - pip:
    - pint-pulsar  # not available for arm64 on conda-forge
