name: CI tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Prepare mamba installation
      env:
          PYTHON_VERSION: '3.10'
      run: |
          # setup correct python version
          sed -i -e "s/- python=.*/- python=$PYTHON_VERSION/g" environment.yml

    - name: Mamba setup
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-downloads: true

    - name: Install dependencies
      run: |
        python --version
        echo "Installing additional pip packages"

        echo "pip install ."
        pip install .

        pip install pytest

    - name: Test with pytest
      run: |
        pytest